---
# ============================================================
# Rôle : monitoring
# Fichier : tasks/main.yml
# Description : Installe Prometheus + Grafana + Loki
# ============================================================

- name: Créer le namespace monitoring
  command: >
    kubectl apply -f
    {{ playbook_dir }}/../kubernetes/monitoring/namespace.yaml
  become: false
  environment:
    KUBECONFIG: "/home/{{ ansible_user }}/.kube/config"




- name: Appliquer le Deployment PostgreSQL Exporter
  command: >
    kubectl apply -f
    {{ playbook_dir }}/../kubernetes/monitoring/postgres-exporter/deployment.yaml
  become: false
  environment:
    KUBECONFIG: "/home/{{ ansible_user }}/.kube/config"
    

- name: Appliquer la ConfigMap Prometheus
  command: >
    kubectl apply -f
    {{ playbook_dir }}/../kubernetes/monitoring/prometheus/configmap.yaml
  become: false
  environment:
    KUBECONFIG: "/home/{{ ansible_user }}/.kube/config"

- name: Appliquer le Deployment Prometheus
  command: >
    kubectl apply -f
    {{ playbook_dir }}/../kubernetes/monitoring/prometheus/deployment.yaml
  become: false
  environment:
    KUBECONFIG: "/home/{{ ansible_user }}/.kube/config"

- name: Appliquer le Service Prometheus
  command: >
    kubectl apply -f
    {{ playbook_dir }}/../kubernetes/monitoring/prometheus/service.yaml
  become: false
  environment:
    KUBECONFIG: "/home/{{ ansible_user }}/.kube/config"

- name: Attendre que Prometheus soit prêt
  command: >
    kubectl rollout status deployment/prometheus
    -n monitoring
    --timeout=120s
  become: false
  environment:
    KUBECONFIG: "/home/{{ ansible_user }}/.kube/config"
  register: prometheus_ready
  retries: 5
  delay: 15
  until: prometheus_ready.rc == 0

- name: Appliquer la ConfigMap Grafana
  command: >
    kubectl apply -f
    {{ playbook_dir }}/../kubernetes/monitoring/grafana/configmap.yaml
  become: false
  environment:
    KUBECONFIG: "/home/{{ ansible_user }}/.kube/config"

- name: Appliquer le Deployment Grafana
  command: >
    kubectl apply -f
    {{ playbook_dir }}/../kubernetes/monitoring/grafana/deployment.yaml
  become: false
  environment:
    KUBECONFIG: "/home/{{ ansible_user }}/.kube/config"

- name: Appliquer le Service Grafana
  command: >
    kubectl apply -f
    {{ playbook_dir }}/../kubernetes/monitoring/grafana/service.yaml
  become: false
  environment:
    KUBECONFIG: "/home/{{ ansible_user }}/.kube/config"

- name: Attendre que Grafana soit prêt
  command: >
    kubectl rollout status deployment/grafana
    -n monitoring
    --timeout=120s
  become: false
  environment:
    KUBECONFIG: "/home/{{ ansible_user }}/.kube/config"
  register: grafana_ready
  retries: 5
  delay: 15
  until: grafana_ready.rc == 0

- name: Appliquer le Deployment Loki et Promtail
  command: >
    kubectl apply -f
    {{ playbook_dir }}/../kubernetes/monitoring/loki/deployment.yaml
  become: false
  environment:
    KUBECONFIG: "/home/{{ ansible_user }}/.kube/config"

- name: Appliquer le Service Loki
  command: >
    kubectl apply -f
    {{ playbook_dir }}/../kubernetes/monitoring/loki/service.yaml
  become: false
  environment:
    KUBECONFIG: "/home/{{ ansible_user }}/.kube/config"

- name: Attendre que Loki soit prêt
  command: >
    kubectl rollout status deployment/loki
    -n monitoring
    --timeout=120s
  become: false
  environment:
    KUBECONFIG: "/home/{{ ansible_user }}/.kube/config"
  register: loki_ready
  retries: 5
  delay: 15
  until: loki_ready.rc == 0

- name: Appliquer le RBAC pour kube-state-metrics
  command: >
    kubectl apply -f
    {{ playbook_dir }}/../kubernetes/monitoring/kube-state-metrics/rbac.yaml
  become: false
  environment:
    KUBECONFIG: "/home/{{ ansible_user }}/.kube/config"


- name: Appliquer le Deployment kube-state-metrics
  command: >
    kubectl apply -f
    {{ playbook_dir }}/../kubernetes/monitoring/kube-state-metrics/deployment.yaml
  become: false
  environment:
    KUBECONFIG: "/home/{{ ansible_user }}/.kube/config"




- name: Redémarrer Prometheus pour prendre en compte le nouveau job
  command: kubectl rollout restart deployment/prometheus -n monitoring
  become: false
  environment:
    KUBECONFIG: "/home/{{ ansible_user }}/.kube/config"


- name: Appliquer l'Ingress monitoring
  command: >
    kubectl apply -f
    {{ playbook_dir }}/../kubernetes/monitoring/ingress/monitoring-ingress.yaml
  become: false
  environment:
    KUBECONFIG: "/home/{{ ansible_user }}/.kube/config"

- name: Vérifier les pods monitoring
  command: kubectl get pods -n monitoring
  become: false
  environment:
    KUBECONFIG: "/home/{{ ansible_user }}/.kube/config"
  register: monitoring_pods

- name: Afficher les pods monitoring
  debug:
    msg: "{{ monitoring_pods.stdout }}"

- name: Résumé installation monitoring
  debug:
    msg: |
      ================================================
      Monitoring installé et prêt !
      Grafana    : http://monitoring.invisithreat.local
      Login      : admin
      Mot de passe : invisithreat2024
      ================================================