apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-data
  namespace: invisithreat
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 3Gi