---
# ============================================================
# MetalLB - L2Advertisement
# Fichier : kubernetes/metallb/l2advertisement.yaml
# Description : Active le mode ARP (Layer 2) pour annoncer
#               les IPs LoadBalancer sur le réseau local.
#               Le nœud K3s répond aux requêtes ARP pour
#               les IPs attribuées par MetalLB.
# ============================================================
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: invisithreat-l2
  namespace: metallb-system
  labels:
    app.kubernetes.io/name: metallb
    managed-by: ansible
spec:
  ipAddressPools:
    - invisithreat-pool