---
# ============================================================
# Prometheus - Service
# Fichier : kubernetes/monitoring/prometheus/service.yaml
# ============================================================
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: monitoring
  labels:
    app: prometheus
    managed-by: ansible
spec:
  selector:
    app: prometheus
  ports:
    - port: 9090
      targetPort: 9090
  type: ClusterIP
---
# ============================================================
# Node Exporter - Service
# ============================================================
apiVersion: v1
kind: Service
metadata:
  name: node-exporter
  namespace: monitoring
  labels:
    app: node-exporter
spec:
  selector:
    app: node-exporter
  ports:
    - port: 9100
      targetPort: 9100
  type: ClusterIP
---
# ============================================================
# Postgres Exporter - Service
# ============================================================
apiVersion: v1
kind: Service
metadata:
  name: postgres-exporter
  namespace: monitoring
  labels:
    app: postgres-exporter
spec:
  selector:
    app: postgres-exporter
  ports:
    - port: 9187
      targetPort: 9187
  type: ClusterIP