apiVersion: v1
kind: Service
metadata:
  name: risk-scoring-engine-svc
  namespace: invisithreat
spec:
  selector:
    app: risk-scoring-engine
  ports:
    - port: 8081
      targetPort: 8081
  type: ClusterIP