# Hardcoded sensitive application details (SAST Finding)
spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
spring.datasource.username=sa
spring.datasource.password=TopSecretProductionPassword2026!
spring.datasource.driver-class-name=org.h2.Driver

# H2 Console Configuration (exposing console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

# Vulnerable Log4j Settings (allow lookup format)
log4j2.formatMsgNoLookups=false
